app:
  scheduler:
    enable: true
    interval: 15s
    force-check-delay: 10s
  base-url-git: https://api.github.com
  base-url-stackoverflow: https://api.stackexchange.com/2.3/questions
  base-url-bot: http://localhost:8090
  git-token: ${GIT_TOKEN}

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
    change-log: liquibase/master.xml
#  datasource:
#    url: jdbc:postgresql://localhost:5432/scrapper
#    username: postgres
#    password: postgres

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
