app:
  telegram-token: ${TELEGRAM_API_KEY}
  base-url-scrapper: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

#client:
#  base-url-scrapper: http://localhost:8080

server:
  port: 8090

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml